cmake_minimum_required(VERSION 3.22)

# Read-only editor adapter. Application JSON is deliberately not parsed here.
get_filename_component(source_root "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
if(NOT DEFINED PNX_BOARD OR NOT PNX_BOARD MATCHES "^[A-Za-z0-9_-]+$")
    message(FATAL_ERROR "PNX_BOARD must name a board profile")
endif()
if(NOT DEFINED PNX_EDITOR_OUTPUT OR PNX_EDITOR_OUTPUT STREQUAL "")
    message(FATAL_ERROR "PNX_EDITOR_OUTPUT is required")
endif()
set(board_dir "${source_root}/boards/${PNX_BOARD}")
if(NOT EXISTS "${board_dir}/board.cmake")
    message(FATAL_ERROR "Unknown board profile: ${PNX_BOARD}")
endif()
include("${board_dir}/board.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/import_ioc.cmake")
pnx_ioc_parse("${PNX_BOARD_IOC}")

function(_pnx_editor_json_string value out)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${out} "\"${value}\"" PARENT_SCOPE)
endfunction()

set(result "{\"formatVersion\":1,\"files\":{},\"hardware\":{}}")
_pnx_editor_json_string("${PNX_BOARD}" value)
string(JSON result SET "${result}" board "${value}")
_pnx_editor_json_string("${PNX_BOARD_FAMILY}" value)
string(JSON result SET "${result}" mcuFamily "${value}")
set(file_ioc "${PNX_BOARD_IOC}")
set(file_board "${board_dir}/board.json")
set(file_params "${PNX_BOARD_PARAMS}")
set(file_robot "${PNX_BOARD_ROBOT_CONFIG}")
foreach(role IN ITEMS ioc board params robot)
    get_filename_component(path "${file_${role}}" ABSOLUTE)
    _pnx_editor_json_string("${path}" value)
    string(JSON result SET "${result}" files ${role} "${value}")
endforeach()
set(PNX_IOC_GPIO_HW ${PNX_IOC_GPIO_INPUT_HW} ${PNX_IOC_GPIO_OUTPUT_HW})
set(PNX_IOC_ADC_HW "")
foreach(entry IN LISTS PNX_IOC_ADC_BLOCKING_CHANNELS)
    string(REGEX REPLACE "\\|.*$" "" resource "${entry}")
    list(APPEND PNX_IOC_ADC_HW "${resource}")
endforeach()
set(PNX_IOC_PWM_HW "${PNX_IOC_PWM_CHANNELS}")
foreach(kind IN ITEMS can uart spi gpio gpio_input gpio_output adc pwm)
    string(TOUPPER "${kind}" upper)
    set(values "[]")
    set(index 0)
    foreach(hw IN LISTS PNX_IOC_${upper}_HW)
        if(NOT kind STREQUAL "pwm")
            string(TOLOWER "${hw}" hw)
        endif()
        _pnx_editor_json_string("${hw}" value)
        string(JSON values SET "${values}" ${index} "${value}")
        math(EXPR index "${index}+1")
    endforeach()
    string(JSON result SET "${result}" hardware ${kind} "${values}")
endforeach()
# GPIO application aliases refer to fixed board roles, not raw IOC pins.
file(READ "${file_board}" editor_board_json)
foreach(direction IN ITEMS input output)
    set(values "[]")
    string(JSON count ERROR_VARIABLE err LENGTH "${editor_board_json}" bindings gpio_${direction}s)
    if(NOT err AND count GREATER 0)
        math(EXPR last "${count}-1")
        foreach(index RANGE 0 ${last})
            string(JSON role MEMBER "${editor_board_json}" bindings gpio_${direction}s ${index})
            _pnx_editor_json_string("${role}" value)
            string(JSON values SET "${values}" ${index} "${value}")
        endforeach()
    endif()
    string(JSON result SET "${result}" hardware gpio_${direction}_role "${values}")
endforeach()
pnx_to_json_bool("${PNX_IOC_HAS_USB}" usb)
string(JSON result SET "${result}" hardware usb "${usb}")


get_filename_component(output "${PNX_EDITOR_OUTPUT}" ABSOLUTE)
get_filename_component(output_dir "${output}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
# Do not invalidate editor caches when the resource snapshot did not change.
if(EXISTS "${output}")
    file(READ "${output}" previous)
    if(previous STREQUAL "${result}\n")
        return()
    endif()
endif()
file(WRITE "${output}.tmp" "${result}\n")
file(RENAME "${output}.tmp" "${output}")
