# Hardware discovery only. pnx_ioc_parse exports PNX_IOC_* facts to its caller.
# Do not read params/robot JSON or decide application feature selection here.
include_guard(GLOBAL)

cmake_minimum_required(VERSION 3.22)

function(pnx_ioc_get_value ioc_lines key out_var)
    set(prefix "${key}=")
    foreach(line ${ioc_lines})
        if(line STREQUAL "" OR line MATCHES "^#")
            continue()
        endif()
        string(LENGTH "${prefix}" prefix_len)
        string(LENGTH "${line}" line_len)
        if(line_len GREATER prefix_len)
            string(SUBSTRING "${line}" 0 ${prefix_len} line_prefix)
            if(line_prefix STREQUAL "${prefix}")
                math(EXPR value_start "${prefix_len}")
                string(SUBSTRING "${line}" ${value_start} -1 value)
                set(${out_var} "${value}" PARENT_SCOPE)
                return()
            endif()
        endif()
    endforeach()
    set(${out_var} "" PARENT_SCOPE)
endfunction()

function(pnx_ioc_parse ioc_file)
    if(NOT EXISTS "${ioc_file}")
        message(FATAL_ERROR "IOC file not found: ${ioc_file}")
    endif()

    file(READ "${ioc_file}" ioc_content)
    string(REPLACE "\r\n" "\n" ioc_content "${ioc_content}")
    string(REPLACE "\r" "\n" ioc_content "${ioc_content}")
    string(REPLACE "\n" ";" ioc_lines "${ioc_content}")

    set(fdcan_hw "")
    set(can_hw "")
    set(uart_hw "")
    set(spi_hw "")
    set(timer_hw "")
    set(pwm_channels "")
    set(adc_regular_candidates "")
    set(has_spi2 FALSE)
    set(has_spi6 FALSE)
    set(has_tim3 FALSE)
    set(has_tim12 FALSE)
    set(has_usb FALSE)
    set(usb_hw "")

    foreach(line ${ioc_lines})
        if(line MATCHES "^Mcu\\.IP[0-9]+=(FDCAN[0-9]+)$")
            list(APPEND fdcan_hw "${CMAKE_MATCH_1}")
            list(APPEND can_hw "${CMAKE_MATCH_1}")
        elseif(line MATCHES "^Mcu\\.IP[0-9]+=(CAN[0-9]+)$")
            list(APPEND can_hw "${CMAKE_MATCH_1}")
        elseif(line MATCHES "^Mcu\\.IP[0-9]+=((USART|UART|LPUART)[0-9]+)$")
            list(APPEND uart_hw "${CMAKE_MATCH_1}")
        elseif(line STREQUAL "Mcu.IPNb")
            continue()
        elseif(line MATCHES "^Mcu\\.IP[0-9]+=(SPI[0-9]+)$")
            list(APPEND spi_hw "${CMAKE_MATCH_1}")
            if(CMAKE_MATCH_1 STREQUAL "SPI2")
                set(has_spi2 TRUE)
            elseif(CMAKE_MATCH_1 STREQUAL "SPI6")
                set(has_spi6 TRUE)
            endif()
        elseif(line MATCHES "^Mcu\\.IP[0-9]+=(TIM[0-9]+)$")
            list(APPEND timer_hw "${CMAKE_MATCH_1}")
            if(CMAKE_MATCH_1 STREQUAL "TIM3")
                set(has_tim3 TRUE)
            elseif(CMAKE_MATCH_1 STREQUAL "TIM12")
                set(has_tim12 TRUE)
            endif()
        elseif(line MATCHES "^Mcu\\.IP[0-9]+=USB_OTG_(FS|HS)$")
            set(has_usb TRUE)
            list(APPEND usb_hw "USB_OTG_${CMAKE_MATCH_1}")
        elseif(line MATCHES "^SH\\.S_(TIM[0-9]+)_CH([1-4])\\.[0-9]+=TIM[0-9]+_CH[1-4],PWM Generation[0-9]+ CH[1-4]$")
            # Single-channel timers may only have TIMx.Channel in IPParameters.
            # Their shared-pin signal declaration carries the explicit PWM mode.
            list(APPEND pwm_channels "${CMAKE_MATCH_1}_CH${CMAKE_MATCH_2}")
        elseif(line MATCHES "^(TIM[0-9]+)\\.Channel-PWM.*CH([1-4])=TIM_CHANNEL_([1-4])$")
            if(NOT CMAKE_MATCH_2 STREQUAL CMAKE_MATCH_3)
                message(FATAL_ERROR "IOC PWM channel declaration is inconsistent: ${line}")
            endif()
            list(APPEND pwm_channels "${CMAKE_MATCH_1}_CH${CMAKE_MATCH_2}")
        elseif(line MATCHES "^(ADC[0-9]+)\\.Channel-([0-9]+).*=(ADC_CHANNEL_([0-9]+))$")
            list(APPEND adc_regular_candidates
                "${CMAKE_MATCH_1}_CH${CMAKE_MATCH_4}:${CMAKE_MATCH_2}")
        endif()
    endforeach()

    list(SORT fdcan_hw)
    list(SORT can_hw)
    list(SORT uart_hw)
    list(REMOVE_DUPLICATES fdcan_hw)
    list(REMOVE_DUPLICATES can_hw)
    list(REMOVE_DUPLICATES uart_hw)
    list(REMOVE_DUPLICATES spi_hw)
    list(REMOVE_DUPLICATES timer_hw)
    list(REMOVE_DUPLICATES pwm_channels)
    list(REMOVE_DUPLICATES adc_regular_candidates)

    set(adc_blocking_channels "")
    foreach(candidate ${adc_regular_candidates})
        if(NOT candidate MATCHES "^(ADC[0-9]+)_CH([0-9]+):([0-9]+)$")
            message(FATAL_ERROR "Invalid ADC regular channel candidate ${candidate}")
        endif()
        set(adc "${CMAKE_MATCH_1}")
        set(adc_channel "${CMAKE_MATCH_2}")
        set(slot "${CMAKE_MATCH_3}")
        pnx_ioc_get_value("${ioc_lines}" "${adc}.NbrOfConversionFlag" conversion_count)
        if(NOT conversion_count STREQUAL "1")
            continue()
        endif()
        set(rank "")
        set(sampling_time "")
        foreach(adc_line ${ioc_lines})
            if(adc_line MATCHES "^${adc}\\.Rank-${slot}.*=([0-9]+)$")
                set(rank "ADC_REGULAR_RANK_${CMAKE_MATCH_1}")
            elseif(adc_line MATCHES "^${adc}\\.SamplingTime-${slot}.*=(ADC_SAMPLETIME_[A-Za-z0-9_]+)$")
                set(sampling_time "${CMAKE_MATCH_1}")
            endif()
        endforeach()
        if(rank STREQUAL "" OR sampling_time STREQUAL "")
            message(FATAL_ERROR "IOC regular channel ${adc} channel ${adc_channel} lacks rank or sampling time")
        endif()
        list(APPEND adc_blocking_channels
            "${adc}_CH${adc_channel}|${rank}|${sampling_time}")
    endforeach()
    list(SORT adc_blocking_channels)

    pnx_natural_sort_hw("${fdcan_hw}" fdcan_hw)
    pnx_natural_sort_hw("${can_hw}" can_hw)
    pnx_natural_sort_hw("${uart_hw}" uart_hw)
    list(SORT spi_hw)
    pnx_natural_sort_hw("${timer_hw}" timer_hw)

    set(PNX_IOC_FDCAN_HW "${fdcan_hw}" PARENT_SCOPE)
    set(PNX_IOC_CAN_HW "${can_hw}" PARENT_SCOPE)
    set(PNX_IOC_UART_HW "${uart_hw}" PARENT_SCOPE)
    set(PNX_IOC_SPI_HW "${spi_hw}" PARENT_SCOPE)
    set(PNX_IOC_TIM_HW "${timer_hw}" PARENT_SCOPE)
    set(PNX_IOC_PWM_CHANNELS "${pwm_channels}" PARENT_SCOPE)
    set(PNX_IOC_ADC_BLOCKING_CHANNELS "${adc_blocking_channels}" PARENT_SCOPE)
    set(PNX_IOC_LINES "${ioc_lines}" PARENT_SCOPE)
    set(PNX_IOC_HAS_SPI2 "${has_spi2}" PARENT_SCOPE)
    set(PNX_IOC_HAS_SPI6 "${has_spi6}" PARENT_SCOPE)
    set(PNX_IOC_HAS_TIM3 "${has_tim3}" PARENT_SCOPE)
    set(PNX_IOC_HAS_TIM12 "${has_tim12}" PARENT_SCOPE)
    set(PNX_IOC_HAS_USB "${has_usb}" PARENT_SCOPE)
    set(PNX_IOC_USB_HW "${usb_hw}" PARENT_SCOPE)
    set(gpio_inputs "")
    set(gpio_outputs "")
    foreach(line ${ioc_lines})
        if(line MATCHES "^(P[A-K][0-9]+)(_C)?\\.Signal=(GPIO_Input|GPXTI[0-9]+)$")
            string(TOLOWER "${CMAKE_MATCH_1}" pin)
            list(APPEND gpio_inputs "${pin}")
        elseif(line MATCHES "^(P[A-K][0-9]+)(_C)?\\.Signal=GPIO_Output$")
            string(TOLOWER "${CMAKE_MATCH_1}" pin)
            list(APPEND gpio_outputs "${pin}")
        endif()
    endforeach()
    list(REMOVE_DUPLICATES gpio_inputs)
    list(REMOVE_DUPLICATES gpio_outputs)
    set(PNX_IOC_GPIO_INPUT_HW "${gpio_inputs}" PARENT_SCOPE)
    set(PNX_IOC_GPIO_OUTPUT_HW "${gpio_outputs}" PARENT_SCOPE)

endfunction()

function(pnx_ioc_timer_has_update_dma ioc_lines timer out_var)
    string(TOUPPER "${timer}" timer_upper)
    set(found FALSE)
    foreach(line ${ioc_lines})
        if(line MATCHES "^Dma\\.Request[0-9]+=${timer_upper}_UP$")
            set(found TRUE)
            break()
        endif()
    endforeach()
    set(${out_var} "${found}" PARENT_SCOPE)
endfunction()

function(pnx_ioc_timer_clock_hz ioc_lines timer out_var)
    string(TOUPPER "${timer}" timer_upper)
    if(timer_upper MATCHES "^TIM(1|8|9|10|11|15|16|17)$")
        set(clock_keys "RCC.Tim1OutputFreq_Value;RCC.APB2TimFreq_Value")
    elseif(timer_upper MATCHES "^TIM(2|3|4|5|6|7|12|13|14|23|24)$")
        set(clock_keys "RCC.Tim2OutputFreq_Value;RCC.APB1TimFreq_Value")
    else()
        message(FATAL_ERROR "Timer ${timer} is not supported by the STM32 timer clock mapping")
    endif()
    set(timer_clock_hz "")
    foreach(clock_key ${clock_keys})
        pnx_ioc_get_value("${ioc_lines}" "${clock_key}" timer_clock_hz)
        if(NOT timer_clock_hz STREQUAL "")
            break()
        endif()
    endforeach()
    if(timer_clock_hz STREQUAL "" OR NOT timer_clock_hz MATCHES "^[0-9]+$")
        message(FATAL_ERROR "IOC does not provide a timer clock for ${timer}; tried ${clock_keys}")
    endif()
    set(${out_var} "${timer_clock_hz}" PARENT_SCOPE)
endfunction()

function(pnx_ioc_uart_index uart_hw_list hw_name out_var)
    string(TOLOWER "${hw_name}" hw_lower)
    set(index -1)
    set(i 0)
    foreach(hw ${uart_hw_list})
        string(TOLOWER "${hw}" entry_lower)
        if(entry_lower STREQUAL hw_lower)
            set(index ${i})
            break()
        endif()
        math(EXPR i "${i} + 1")
    endforeach()
    set(${out_var} "${index}" PARENT_SCOPE)
endfunction()

function(pnx_ioc_hw_in_list hw_list hw_name out_var)
    pnx_ioc_uart_index("${hw_list}" "${hw_name}" index)
    if(index GREATER_EQUAL 0)
        set(${out_var} TRUE PARENT_SCOPE)
    else()
        set(${out_var} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(pnx_ioc_fdcan_frame_format ioc_lines hw out_var)
    string(TOUPPER "${hw}" hw_upper)
    pnx_ioc_get_value("${ioc_lines}" "${hw_upper}.FrameFormat" frame_format)
    if(frame_format STREQUAL "FDCAN_FRAME_FD_BRS")
        set(${out_var} "fd_brs" PARENT_SCOPE)
    elseif(frame_format STREQUAL "FDCAN_FRAME_FD_NO_BRS")
        set(${out_var} "fd_no_brs" PARENT_SCOPE)
    else()
        set(${out_var} "classic" PARENT_SCOPE)
    endif()
endfunction()

function(pnx_ioc_fdcan_ext_filters ioc_lines hw out_var)
    string(TOUPPER "${hw}" hw_upper)
    pnx_ioc_get_value("${ioc_lines}" "${hw_upper}.ExtFiltersNbr" ext_filters)
    if(ext_filters STREQUAL "")
        set(ext_filters "0")
    endif()
    set(${out_var} "${ext_filters}" PARENT_SCOPE)
endfunction()

function(pnx_ioc_fdcan_std_filters ioc_lines hw out_var)
    string(TOUPPER "${hw}" hw_upper)
    pnx_ioc_get_value("${ioc_lines}" "${hw_upper}.StdFiltersNbr" std_filters)
    if(std_filters STREQUAL "")
        set(std_filters "0")
    endif()
    set(${out_var} "${std_filters}" PARENT_SCOPE)
endfunction()

function(pnx_ioc_uart_has_dma ioc_lines hw direction out_var)
    string(TOUPPER "${hw}" hw_upper)
    set(found FALSE)
    foreach(line ${ioc_lines})
        if(line MATCHES "^Dma\\.Request[0-9]+=${hw_upper}_${direction}$")
            set(found TRUE)
        endif()
    endforeach()
    set(${out_var} "${found}" PARENT_SCOPE)
endfunction()

function(pnx_ioc_spi_has_irq ioc_lines hw out_var)
    string(TOUPPER "${hw}" hw_upper)
    pnx_ioc_get_value("${ioc_lines}" "NVIC.${hw_upper}_IRQn" irq_config)
    if(irq_config MATCHES "^true")
        set(${out_var} TRUE PARENT_SCOPE)
    else()
        set(${out_var} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(pnx_ioc_spi_has_dma ioc_lines hw direction out_var)
    string(TOUPPER "${hw}" hw_upper)
    set(found FALSE)
    foreach(line ${ioc_lines})
        if(line MATCHES "^Dma\\.Request[0-9]+=${hw_upper}_${direction}$")
            set(found TRUE)
        endif()
    endforeach()
    set(${out_var} "${found}" PARENT_SCOPE)
endfunction()

function(pnx_hw_to_handle hw out_var)
    string(TOLOWER "${hw}" hw_lower)
    if(hw_lower MATCHES "^usart([0-9]+)$")
        set(${out_var} "&huart${CMAKE_MATCH_1}" PARENT_SCOPE)
    elseif(hw_lower MATCHES "^uart([0-9]+)$")
        set(${out_var} "&huart${CMAKE_MATCH_1}" PARENT_SCOPE)
    elseif(hw_lower MATCHES "^lpuart([0-9]+)$")
        set(${out_var} "&hlpuart${CMAKE_MATCH_1}" PARENT_SCOPE)
    else()
        set(${out_var} "&h${hw_lower}" PARENT_SCOPE)
    endif()
endfunction()

function(pnx_hw_to_dma_handle hw direction out_var)
    string(TOLOWER "${hw}" hw_lower)
    string(TOLOWER "${direction}" dir_lower)
    set(${out_var} "&hdma_${hw_lower}_${dir_lower}" PARENT_SCOPE)
endfunction()

function(pnx_to_json_bool cmake_bool out_var)
    if(cmake_bool)
        set(${out_var} "true" PARENT_SCOPE)
    else()
        set(${out_var} "false" PARENT_SCOPE)
    endif()
endfunction()

function(pnx_natural_sort_hw hw_list out_var)
    set(keys "")
    foreach(hw ${hw_list})
        string(TOUPPER "${hw}" hw_upper)
        if(hw_upper MATCHES "^(FDCAN|CAN|USART|UART|LPUART)([0-9]+)$")
            set(prefix "${CMAKE_MATCH_1}")
            set(num "${CMAKE_MATCH_2}")
            string(LENGTH "${num}" num_len)
            math(EXPR pad_len "3 - ${num_len}")
            if(pad_len LESS 0)
                set(pad_len 0)
            endif()
            string(REPEAT "0" ${pad_len} padding)
            set(key "${prefix}_${padding}${num}")
        else()
            set(key "${hw_upper}")
        endif()
        list(APPEND keys "${key}:${hw}")
    endforeach()
    list(SORT keys)
    set(sorted "")
    foreach(entry ${keys})
        string(REGEX REPLACE "^[^:]+:(.*)$" "\\1" hw "${entry}")
        list(APPEND sorted "${hw}")
    endforeach()
    set(${out_var} "${sorted}" PARENT_SCOPE)
endfunction()
