# Application parameters are owned by params.json; hardware still uses the
# template's IOC/board/robot generators. This file only emits dart constants.
string(JSON PNX_DART_ENABLED ERROR_VARIABLE dart_error GET "${params_json}" dart enabled)
if(dart_error)
    set(PNX_DART_ENABLED OFF)
endif()
if(NOT PNX_DART_ENABLED)
    return()
endif()
if(NOT ENABLE_USBX OR NOT ENABLE_DR16)
    message(FATAL_ERROR "The migrated dart application requires build.usbx=true and remoter.source=dr16")
endif()

set(dart_header "#pragma once\n// Generated from params.json and robot.json. Do not edit.\n#include <cstdint>\n#include \"configuration.hpp\"\nnamespace dart::cfg {\n")
function(dart_fields section type)
    string(APPEND dart_header "namespace ${section} {\n")
    foreach(field IN LISTS ARGN)
        string(JSON value ERROR_VARIABLE error GET "${params_json}" dart ${section} ${field})
        if(error)
            message(FATAL_ERROR "dart.${section}.${field} is required")
        endif()
        if(type STREQUAL "bool")
            if(value)
                set(value "true")
            else()
                set(value "false")
            endif()
        elseif(NOT value MATCHES "^-?[0-9]+([.][0-9]+)?([eE][-+]?[0-9]+)?$")
            message(FATAL_ERROR "dart.${section}.${field} must be numeric")
        elseif(type STREQUAL "float")
            if(NOT value MATCHES "[.eE]")
                string(APPEND value ".0")
            endif()
            string(APPEND value "f")
        elseif(type STREQUAL "std::uint32_t" AND NOT value MATCHES "^[0-9]+$")
            message(FATAL_ERROR "dart.${section}.${field} must be a nonnegative integer")
        endif()
        string(APPEND dart_header "inline constexpr ${type} ${field} = ${value};\n")
        if(field MATCHES "(_ticks|_priority)$" AND type STREQUAL "std::uint32_t")
            if(value LESS 1 OR (field MATCHES "_priority$" AND value GREATER 31))
                message(FATAL_ERROR "dart.${section}.${field} is outside the ThreadX range")
            endif()
        endif()
    endforeach()
    string(APPEND dart_header "}\n")
    set(dart_header "${dart_header}" PARENT_SCOPE)
endfunction()

dart_fields(motor std::uint32_t thread_priority period_ticks alive_check_ticks
    string_max_current_ma string_accel_rpm_s trigger_open_us trigger_idle_us trigger_hold_ticks)
dart_fields(motor float initial_syn_spd syn_kp syn_ki syn_kd syn_max_out syn_max_iout
    string_kp string_ki string_kd string_max_out string_max_iout
    string_manual_max_rpm string_force_limit_kg string_deadband)
dart_fields(launcher std::uint32_t thread_priority period_ticks string_relax_ticks
    syn_tq_error_ticks trigger_ready_ticks ready_fire_ticks firing_ticks fire_done_ticks)
dart_fields(launcher float gantry_deadband syn_deadband tension_deadband
    string_relax_spd string_relax_min_kg syn_pos_1 syn_pos_2 syn_pos_3 syn_pos_5
    syn_slow_spd force_error_kg syn_tq_error)
dart_fields(system std::uint32_t thread_priority period_ticks vision_open_ticks
    vision_closed_ticks referee_stable_ticks door_stable_ticks)
dart_fields(system bool auto_on_boot fixed_aim legacy_game_gate)
dart_fields(system float yaw_fast_threshold yaw_mid_threshold yaw_deadband
    yaw_fast_spd yaw_mid_spd yaw_slow_spd syn_manual_scale trigger_threshold)
dart_fields(system int target_override)
dart_fields(sensor std::uint32_t thread_priority period_ticks timeout_ticks)
dart_fields(sensor float force_scale)
dart_fields(host std::uint32_t thread_priority period_ticks frame_timeout_ticks telemetry_ticks)
dart_fields(vision bool verify_crc)
dart_fields(monitor std::uint32_t thread_priority period_ticks phase_ticks)

# Protocol addresses/direction are device composition, not BSP policy.
string(APPEND dart_header "namespace motor {\n")
string(JSON motor_count LENGTH "${robot_json}" devices motors list)
math(EXPR motor_last "${motor_count} - 1")
foreach(index RANGE ${motor_last})
    string(JSON motor_name GET "${robot_json}" devices motors list ${index} name)
    if(motor_name STREQUAL "string_l" OR motor_name STREQUAL "string_r")
        string(JSON direction GET "${robot_json}" devices motors list ${index} positive_dir)
        if(NOT direction MATCHES "^[01]$")
            message(FATAL_ERROR "${motor_name}.positive_dir must be 0 or 1")
        endif()
        string(APPEND dart_header "inline constexpr std::uint8_t ${motor_name}_positive_dir = ${direction};\n")
    endif()
endforeach()
string(APPEND dart_header "}\ninline constexpr dart_param calibration[] = {\n")
string(JSON count LENGTH "${params_json}" dart calibration)
if(NOT count EQUAL 16)
    message(FATAL_ERROR "dart.calibration requires 16 entries in dart ID order")
endif()
foreach(index RANGE 0 15)
    math(EXPR id "${index} + 1")
    string(APPEND dart_header "{${id}, ")
    foreach(field IN ITEMS yaw_offset tension_kg_base tension_kg_outpost)
        string(JSON value GET "${params_json}" dart calibration ${index} ${field})
        string(APPEND dart_header "static_cast<float>(${value}), ")
    endforeach()
    string(APPEND dart_header "},\n")
endforeach()
string(APPEND dart_header "};\ninline constexpr table_point distance_table[] = {\n")
string(JSON count LENGTH "${params_json}" dart distance_table)
if(count LESS 1 OR count GREATER 128)
    message(FATAL_ERROR "dart.distance_table requires 1..128 entries")
endif()
math(EXPR last "${count} - 1")
foreach(index RANGE ${last})
    string(JSON id GET "${params_json}" dart distance_table ${index} id)
    string(APPEND dart_header "{${id}, ")
    foreach(field IN ITEMS distance yaw_offset tension_kg)
        string(JSON value GET "${params_json}" dart distance_table ${index} ${field})
        string(APPEND dart_header "static_cast<float>(${value}), ")
    endforeach()
    string(APPEND dart_header "},\n")
endforeach()
string(APPEND dart_header "};\ninline constexpr int sequence[4] = {")
string(JSON count LENGTH "${params_json}" dart sequence)
if(NOT count EQUAL 4)
    message(FATAL_ERROR "dart.sequence requires four dart IDs")
endif()
foreach(index RANGE 0 3)
    string(JSON id GET "${params_json}" dart sequence ${index})
    if(id LESS 1 OR id GREATER 16)
        message(FATAL_ERROR "dart.sequence ID must be in 1..16")
    endif()
    string(APPEND dart_header "${id}, ")
endforeach()
string(JSON pre_tension GET "${params_json}" dart pre_tension_kg)
string(APPEND dart_header "};\ninline constexpr float pre_tension_kg = static_cast<float>(${pre_tension});\n}\n")
file(CONFIGURE OUTPUT "${PNX_EMBEDDED_GENERATED_DIR}/dart_config.hpp" CONTENT "${dart_header}" @ONLY)
